// clock_dial_bg.h — declares the pre-converted dial background image
// consumed by DispDriverGc9a01RoundClock::setDialBackground(). See
// clock_dial_bg_data.cpp (generated by scripts/convert_photo.py, not
// hand-edited) for the actual pixel data. Source art-deco clock face
// generated by Google Gemini, already hand-free (numerals/bezel/sunburst
// only) so the dynamic hands drawn in code have a clean background to
// sit on top of.

#pragma once

#include "lvgl.h"

extern const lv_image_dsc_t clock_dial_bg;
