// photo_face.h — declares the pre-converted image data consumed by
// DispDriverGc9a01RoundClock::setPhotos() (round-robin photo rotation,
// see that method's doc comment). Each extern is generated by
// scripts/convert_photo.py from a source image under photos/, not
// hand-edited — see the matching main/<name>_data.cpp for the actual
// pixel data. Source images generated by Google Gemini.

#pragma once

#include "lvgl.h"

extern const lv_image_dsc_t photo_face_scrivener;
extern const lv_image_dsc_t photo_face_warden;
extern const lv_image_dsc_t photo_face_archivist;
extern const lv_image_dsc_t photo_face_test_signal;
