#!/usr/bin/env python3
# Converts a square source image into a main/*_data.cpp file — an
# RGB565 lv_image_dsc_t consumed by
# DispDriverGc9a01RoundClock::setPhotos() (see photo_face.h and
# temporal_anomaly_app.cpp's setupHardware()). The photo rotation
# supports more than one image (round-robin, see setPhotos()'s doc
# comment) so each image gets its own C identifier and output file.
#
# Usage: scripts/convert_photo.py path/to/source.jpg [var_name]
#   var_name defaults to "photo_face_man" (the original single-photo
#   name); output file is main/<var_name>_data.cpp.
#
# Remember to update the attribution in the generated file's header
# comment and README.md's "Photo face" section if the new source image
# comes from a different generator/photographer than Google Gemini.

import os
import sys
from PIL import Image

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
W, H = 240, 240

if len(sys.argv) not in (2, 3):
    print(f"usage: {sys.argv[0]} path/to/source_image [var_name]", file=sys.stderr)
    sys.exit(1)
src_path = sys.argv[1]
VAR = sys.argv[2] if len(sys.argv) == 3 else "photo_face_man"
DST = os.path.join(REPO_ROOT, "main", f"{VAR}_data.cpp")
src_rel = os.path.relpath(src_path, REPO_ROOT)

im = Image.open(src_path).convert("RGB")
im = im.resize((W, H), Image.LANCZOS)

pixels = list(im.getdata())
data = bytearray()
for r, g, b in pixels:
    v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
    data += v.to_bytes(2, "little")

with open(DST, "w") as f:
    f.write(f'// Generated from {src_rel} by scripts/convert_photo.py\n')
    f.write('// (240x240 RGB565, source was already square) -- not meant to be\n')
    f.write('// hand-edited. Source image generated by Google Gemini.\n\n')
    f.write('#include "photo_face.h"\n\n')
    f.write(f"static const uint8_t {VAR}_map[] = {{\n")
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        f.write("    " + ",".join(f"0x{b:02x}" for b in chunk) + ",\n")
    f.write("};\n\n")
    f.write(f"const lv_image_dsc_t {VAR} = {{\n")
    f.write("    .header = {\n")
    f.write("        .magic = LV_IMAGE_HEADER_MAGIC,\n")
    f.write("        .cf = LV_COLOR_FORMAT_RGB565,\n")
    f.write("        .flags = 0,\n")
    f.write(f"        .w = {W},\n")
    f.write(f"        .h = {H},\n")
    f.write(f"        .stride = {W * 2},\n")
    f.write("        .reserved_2 = 0,\n")
    f.write("    },\n")
    f.write(f"    .data_size = sizeof({VAR}_map),\n")
    f.write(f"    .data = {VAR}_map,\n")
    f.write("    .reserved = nullptr,\n")
    f.write("    .reserved_2 = nullptr,\n")
    f.write("};\n")

print("wrote", DST, "pixel bytes:", len(data))
